Gästebuch/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Gästebuch.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Gästebuch/Controllers/LoginSysController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Gästebuch.Models;

namespace GaesteBuch.Controllers
{
    public class LoginSysController : Controller
    {
        // GET: LoginSys
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Autho(tbl_Admin admin, tbl_Log tbl_Log)
        {
            using (GästebuchEntities1 db = new GästebuchEntities1())
            {
                var X = admin.Passwort.GetHashCode();
                string y = X.ToString();
                var userInhalt = db.tbl_Admin.Where(x => x.Benutzername == admin.Benutzername && x.Passwort == y && admin.twoStep == "133").FirstOrDefault();
                if (userInhalt == null )
                {
                    admin.ErrorMsg = "Invalid Data";
                    return View("~/Views/Home/Contact.cshtml", admin);
                }
                else
                {
                    Session["userID"] = userInhalt.ID;
                    Session["userName"] = admin.Benutzername;
                    
                    
                    tbl_Log.ID = Guid.NewGuid();
                    tbl_Log.Vorgang = "Admin *"+ userInhalt.Benutzername +"* hat sich eingeloggt";
                    tbl_Log.Datum = DateTime.Now;
                    tbl_Log.IP_Adresse = Request.UserHostAddress;
                    db.tbl_Log.Add(tbl_Log);

                    db.SaveChanges();

                    return RedirectToAction("Index", "tbl_Eintrag");
                }
            }
        }
        public ActionResult LogOut(tbl_Log tbl_Log)
        {
            using (GästebuchEntities1 db = new GästebuchEntities1())
            {
                tbl_Log.ID = Guid.NewGuid();
                tbl_Log.Vorgang = "Admin *" + Session["userName"] + "* hat sich ausgeloggt";
                tbl_Log.Datum = DateTime.Now;
                tbl_Log.IP_Adresse = Request.UserHostAddress;
                db.tbl_Log.Add(tbl_Log);

                db.SaveChanges();
            }
                Session.Abandon();

            return RedirectToAction("Index", "Home");
        }
    }
}

Gästebuch/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Gästebuch/Views/Home/Contact.cshtml
@model Gästebuch.Models.tbl_Admin
@{
    ViewBag.Title = "Login";
}

<div class="wrapper fadeInDown">
    <div id="formContent">
        @using (Html.BeginForm("Autho", "LoginSys", FormMethod.Post))
        {
            <!-- Login Form -->
            <h2 class="h2-login">Admin Login</h2>
            <form>
                @Html.EditorFor(model => model.Benutzername, new { htmlAttributes = new { @class = "", @id = "login", placeholder = "Username", name = "login", } })
                <!--Error Message-->
                <p>@Html.ValidationMessageFor(model => model.Benutzername)</p>

                @Html.EditorFor(model => model.Passwort, new { htmlAttributes = new { @class = "", @id = "password", placeholder = "Password", name = "login", type = "password" } })
                <!--Error Message-->
                <p>@Html.ValidationMessageFor(model => model.Passwort)</p>

                @Html.EditorFor(model => model.twoStep, new { htmlAttributes = new { @class = "", @id = "twoStep", placeholder = "Modul ...", name = "login" } })
                <!--Error Message-->
                <p>@Html.ValidationMessageFor(model => model.twoStep)</p>
                <br />
                <input type="submit" class="fadeIn fourth" value="Log In">

                <p>@Html.DisplayFor(model => model.ErrorMsg)</p>

            </form>
        }
        <!-- Remind Passowrd -->
        <script src="~/Scripts/jquery-3.4.1.min.js"></script>
        <script src="~/Scripts/jquery.validate.min.js"></script>
        <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    </div>
</div>

Gästebuch/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Gästebuch</h1>
    <p class="lead">Hier kannst du eine Bewertung, Verbesserung oder einfach nur deinen Senf hinzu geben!</p>
</div>


<div class="row">
    <div class="col-md-4">
        <h2>Einträge lesen</h2>
        <p>
            schaue dir alle bisherigen Einträge unserer Bar an und lese spanende und ehrliche Rezensionen unserer Bar.
        </p>
        <p><a class="btn btn-default" href="../tbl_Eintrag">anzeigen &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Einträge erstellen</h2>
        <p>erstelle deine eigenen Einträge um deine eigene Meinung zu vertreten.</p>
        <p><a class="btn btn-default" href="../tbl_Eintrag/Create">erstellen &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Adminloggin</h2>
        <p></p>
        <p><a class="btn btn-default" href="Contact">loggin &raquo;</a></p>
    </div>
</div>